# Используем официальный образ Go
FROM golang:1.21-alpine

# Устанавливаем необходимые пакеты
RUN apk add --no-cache ca-certificates tzdata

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем исходные файлы проекта
COPY Robots ./Robots

# Собираем программу
RUN go build -o robot-app ./Robots/robot_solution.go

# Запускаем приложение
CMD ["/app/robot-app"] 