# Используем официальный образ Go
FROM golang:1.21-alpine

# Устанавливаем необходимые пакеты
RUN apk add --no-cache git ca-certificates tzdata

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем исходные файлы проекта
COPY Exchange ./Exchange
COPY go.mod ./
COPY go.sum ./

# Устанавливаем зависимости
RUN go mod download

# Собираем программу
RUN go build -o exchange-app ./Exchange/exchange.go

# Запускаем приложение
CMD ["/app/exchange-app"] 